services/Zenoss.core.full/Infrastructure/HBase/HMaster/service.json, services/Zenoss.core.full/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.core/Infrastructure/HBase/HMaster/service.json, services/Zenoss.core/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.nfvimon/Infrastructure/HBase/HMaster/service.json, services/Zenoss.nfvimon/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/service.json, services/Zenoss.resmgr.lite/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.resmgr/Infrastructure/HBase/HMaster/service.json, services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.saas/HBase/HMaster/service.json, services/Zenoss.saas/HBase/RegionServer/service.json, services/ucspm.lite/Infrastructure/HBase/HMaster/service.json, services/ucspm.lite/Infrastructure/HBase/RegionServer/service.json, services/ucspm/Infrastructure/HBase/HMaster/service.json, services/ucspm/Infrastructure/HBase/RegionServer/service.json
=> fixes ZEN-24395: HBase RegionServer logs aren't captured in logstash

services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/Zenoss.core.full/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.core/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/Zenoss.core/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.saas/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.saas/localhost/localhost/zenpython/service.json, services/Zenoss.saas/localhost/zenhub/service.json, services/ucspm.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/ucspm.lite/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/ucspm.lite/Zenoss/Collection/localhost/zenhub/service.json, services/ucspm/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/ucspm/Zenoss/Collection/localhost/localhost/zenpython/service.json, services/ucspm/Zenoss/Collection/localhost/zenhub/service.json
This is port from : 
https://github.com/zenoss/zenoss-service/pull/216 
and 
https://github.com/zenoss/zenoss-service/pull/219
=> ZEN-23867: add new healthchecks

services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.core.full/service.json, services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.core/service.json, services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.resmgr/service.json, services/Zenoss.saas/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/Zenoss.saas/service.json, services/ucspm.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/ucspm.lite/service.json, services/ucspm/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf, services/ucspm/service.json
This updates the zproxy config file with improved PageSpeed options, dynamic Zope upstreams, and a short-circuit config to go directly to the filesystem for static files rather than fetching from ZServer.
=> ZEN-23950: Update zproxy for better Zope performance

services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.core/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/Zenoss.core/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.saas/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.saas/localhost/localhost/zenmail/service.json, services/Zenoss.saas/localhost/localhost/zenpop3/service.json, services/ucspm.lite/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/ucspm.lite/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/ucspm/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/ucspm/Zenoss/Collection/localhost/localhost/zenpop3/service.json
Fix provide changes like correct printf format for zenpop3 and zenmail datapoints format.
[Jira](https://jira.zenoss.com/browse/ZEN-25580)
=> ZEN-25580 fix zenpop3 and zenmail datapoints format

services/ucspm.lite/service.json, services/ucspm/service.json
[Jira](https://jira.zenoss.com/browse/ZEN-25932)
=> ZEN-25932:Bump version to 2.0.3

services/Zenoss.core.full/Zenoss/Events/zeneventserver/service.json, services/Zenoss.core/Zenoss/Events/zeneventserver/service.json, services/Zenoss.resmgr.lite/Zenoss/Events/zeneventserver/service.json, services/Zenoss.resmgr/Zenoss/Events/zeneventserver/service.json, services/nfvi/Zenoss/Events/zeneventserver/service.json, services/ucspm.lite/Zenoss/Events/zeneventserver/service.json, services/ucspm/Zenoss/Events/zeneventserver/service.json
https://jira.zenoss.com/browse/ZEN-25946
=> Restrict zeneventserver to just 1 instance

services/Zenoss.core.full/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/Zenoss.core.full/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/Zenoss.core/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/Zenoss.core/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/Zenoss.resmgr.lite/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/Zenoss.resmgr.lite/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/Zenoss.resmgr/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/Zenoss.resmgr/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/Zenoss.saas/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/Zenoss.saas/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/nfvi/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/nfvi/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/ucspm.lite/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/ucspm.lite/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/ucspm/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, services/ucspm/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, testdata/model/Zenoss.core.fake/Zenoss/Metrics/CentralQuery/-CONFIGS-/opt/zenoss/etc/central-query/configuration.yaml, testdata/model/Zenoss.core.fake/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml
=> reference global.conf properties in service context

.gitignore, services/Zenoss.core.full/Infrastructure/opentsdb/reader/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.core.full/Infrastructure/opentsdb/writer/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.core/Infrastructure/opentsdb/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.resmgr.lite/Infrastructure/opentsdb/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.resmgr/Infrastructure/opentsdb/reader/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.resmgr/Infrastructure/opentsdb/writer/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.saas/opentsdb/reader/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/Zenoss.saas/opentsdb/writer/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/datastack/Infrastructure/opentsdb/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/nfvi/Infrastructure/opentsdb/reader/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/nfvi/Infrastructure/opentsdb/writer/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/ucspm.lite/Infrastructure/Imp4OpenTSDB/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/ucspm/Infrastructure/Imp4OpenTSDB/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/ucspm/Infrastructure/opentsdb/reader/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf, services/ucspm/Infrastructure/opentsdb/writer/-CONFIGS-/opt/zenoss/etc/opentsdb/opentsdb.conf
Cherry-picked from https://github.com/zenoss/zenoss-service/pull/372
https://jira.zenoss.com/browse/ZEN-27100
Part of https://jira.zenoss.com/browse/ZEN-27081
=> Add skip unresolved tags setting to opentsdb config

services/Zenoss.core.full/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/Zenoss.resmgr/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/Zenoss.saas/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/nfvi/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/ucspm/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, testdata/model/Zenoss.core.fake/Zenoss/User-Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf
[Jira](https://jira.zenoss.com/browse/ZEN-23510)
=> ZEN-23510 Change 'zserver-threads' to 7

services/Zenoss.core.full/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/Zenoss.resmgr/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/Zenoss.saas/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/nfvi/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, services/ucspm/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf, testdata/model/Zenoss.core.fake/Zenoss/User-Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zauth/zauth-zope.conf
[Jira](https://jira.zenoss.com/browse/ZEN-27289), port of #381, migration for this change: zenoss/zenoss-prodbin#2279
=> ZEN-27289 Change 'zserver-threads' to 7

services/ucspm.lite/service.json, services/ucspm/service.json
=> Bump UCS-PM version to 2.5.0

services/Zenoss.core.full/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/Zenoss.core.full/Infrastructure/Solr/service.json, services/Zenoss.core/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/Zenoss.core/Infrastructure/Solr/service.json, services/Zenoss.resmgr.lite/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/Zenoss.resmgr.lite/Infrastructure/Solr/service.json, services/Zenoss.resmgr/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/Zenoss.resmgr/Infrastructure/Solr/service.json, services/nfvi/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/nfvi/Infrastructure/Solr/service.json, services/ucspm.lite/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/ucspm.lite/Infrastructure/Solr/service.json, services/ucspm/Infrastructure/Solr/-CONFIGS-/opt/solr/server/solr/configsets/zenoss_model/conf/solrconfig.xml, services/ucspm/Infrastructure/Solr/service.json
=> Expose Solr config file

pkg/makefile
Updating SERVICE_ARCHIVE so the IsAudit flag is recognized.
=> Update Serviced Archive Version

services/Zenoss.core.full/Infrastructure/RabbitMQ/service.json, services/Zenoss.core/Infrastructure/RabbitMQ/service.json, services/Zenoss.resmgr.lite/Infrastructure/RabbitMQ/service.json, services/Zenoss.resmgr/Infrastructure/RabbitMQ/service.json, services/Zenoss.saas/RabbitMQ/service.json, services/nfvi/Infrastructure/RabbitMQ/service.json, services/ucspm.lite/Infrastructure/RabbitMQ/service.json, services/ucspm/Infrastructure/RabbitMQ/service.json
https://jira.zenoss.com/browse/ZEN-28155
Fix log file locations for rabbit so they show up in Kibana
=> Fix rabbit log locations to match node name

services/Zenoss.core.full/Infrastructure/opentsdb/reader/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.core.full/Infrastructure/opentsdb/reader/service.json, services/Zenoss.core.full/Infrastructure/opentsdb/writer/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.core.full/Infrastructure/opentsdb/writer/service.json, services/Zenoss.core/Infrastructure/opentsdb/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.core/Infrastructure/opentsdb/service.json, services/Zenoss.resmgr.lite/Infrastructure/opentsdb/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.resmgr.lite/Infrastructure/opentsdb/service.json, services/Zenoss.resmgr/Infrastructure/opentsdb/reader/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.resmgr/Infrastructure/opentsdb/reader/service.json, services/Zenoss.resmgr/Infrastructure/opentsdb/writer/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.resmgr/Infrastructure/opentsdb/writer/service.json, services/Zenoss.saas/opentsdb/reader/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.saas/opentsdb/reader/service.json, services/Zenoss.saas/opentsdb/writer/-CONFIGS-/opt/opentsdb/src/logback.xml, services/Zenoss.saas/opentsdb/writer/service.json, services/datastack/Infrastructure/opentsdb/-CONFIGS-/opt/opentsdb/src/logback.xml, services/nfvi/Infrastructure/opentsdb/reader/-CONFIGS-/opt/opentsdb/src/logback.xml, services/nfvi/Infrastructure/opentsdb/reader/service.json, services/nfvi/Infrastructure/opentsdb/writer/-CONFIGS-/opt/opentsdb/src/logback.xml, services/nfvi/Infrastructure/opentsdb/writer/service.json, services/ucspm.lite/Infrastructure/opentsdb/-CONFIGS-/opt/opentsdb/src/logback.xml, services/ucspm.lite/Infrastructure/opentsdb/service.json, services/ucspm/Infrastructure/opentsdb/reader/-CONFIGS-/opt/opentsdb/src/logback.xml, services/ucspm/Infrastructure/opentsdb/reader/service.json, services/ucspm/Infrastructure/opentsdb/writer/-CONFIGS-/opt/opentsdb/src/logback.xml, services/ucspm/Infrastructure/opentsdb/writer/service.json
Backport PR #427 from `'develop` to `support/5.3.x`
=> ZEN-27916 Excessive logging in opentsdb 

services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenmail/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenpop3/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.resmgr/Zenoss/Events/zenactiond/service.json
Fixes ZEN-28072
For the upgrade, see https://github.com/zenoss/zenoss-prodbin/pull/2616
=> Fix log filters for zenmail, zenpope, zenhub and zenactiond

services/Zenoss.core.full/FILTERS/rabbitmq.conf, services/Zenoss.core/FILTERS/rabbitmq.conf, services/Zenoss.resmgr.lite/FILTERS/rabbitmq.conf, services/Zenoss.resmgr/FILTERS/rabbitmq.conf, services/Zenoss.saas/FILTERS/rabbitmq.conf, services/nfvi/FILTERS/rabbitmq.conf, services/ucspm.lite/FILTERS/rabbitmq.conf, services/ucspm/FILTERS/rabbitmq.conf
https://jira.zenoss.com/browse/ZEN-28095
https://jira.zenoss.com/browse/ZEN-28094
This implements the log filters for RabbitMQ per the aforementioned tickets.
=> All requested items implemented for rabbitmq filters.

services/Zenoss.core.full/FILTERS/glog.conf, services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/zminion/service.json, services/Zenoss.core.full/Zenoss/Metrics/MetricShipper/service.json, services/Zenoss.core/FILTERS/glog.conf, services/Zenoss.core/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/Zenoss.core/Zenoss/Collection/localhost/localhost/zminion/service.json, services/Zenoss.core/Zenoss/Metrics/MetricShipper/service.json, services/Zenoss.resmgr.lite/FILTERS/glog.conf, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zminion/service.json, services/Zenoss.resmgr.lite/Zenoss/Metrics/MetricShipper/service.json, services/Zenoss.resmgr/FILTERS/glog.conf, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zminion/service.json, services/Zenoss.resmgr/Zenoss/Metrics/MetricShipper/service.json, services/ucspm.lite/FILTERS/glog.conf, services/ucspm.lite/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/ucspm.lite/Zenoss/Collection/localhost/localhost/zminion/service.json, services/ucspm.lite/Zenoss/Metrics/MetricShipper/service.json, services/ucspm/FILTERS/glog.conf, services/ucspm/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/ucspm/Zenoss/Collection/localhost/localhost/zminion/service.json, services/ucspm/Zenoss/Metrics/MetricShipper/service.json
Fixes ZEN-28075
For the corresponding service migration, see https://github.com/zenoss/zenoss-prodbin/pull/2623
=> Add log filters for zminion and metricshipper

services/Zenoss.core.full/FILTERS/zeneventserver-stdio.conf, services/Zenoss.core.full/Zenoss/Events/zeneventserver/service.json, services/Zenoss.core/FILTERS/zeneventserver-stdio.conf, services/Zenoss.core/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.core/Zenoss/Events/zeneventserver/service.json, services/Zenoss.resmgr.lite/FILTERS/zeneventserver-stdio.conf, services/Zenoss.resmgr.lite/Zenoss/Events/zeneventserver/service.json, services/Zenoss.resmgr/FILTERS/zeneventserver-stdio.conf, services/Zenoss.resmgr/Zenoss/Events/zeneventserver/service.json, services/Zenoss.saas/FILTERS/zeneventserver-stdio.conf, services/Zenoss.saas/zeneventserver/service.json, services/nfvi/FILTERS/zeneventserver-stdio.conf, services/nfvi/Zenoss/Events/zeneventserver/service.json, services/ucspm.lite/FILTERS/zeneventserver-stdio.conf, services/ucspm.lite/Zenoss/Events/zeneventserver/service.json, services/ucspm/FILTERS/zeneventserver-stdio.conf, services/ucspm/Zenoss/Events/zeneventserver/service.json
This pull request addresses: https://jira.zenoss.com/browse/ZEN-28080
=> Added in new filter and service def for zeneventserver-stdio*.log files.

services/Zenoss.core.full/FILTERS/zookeeper.conf, services/Zenoss.core.full/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.core/FILTERS/zookeeper.conf, services/Zenoss.core/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.resmgr.lite/FILTERS/zookeeper.conf, services/Zenoss.resmgr.lite/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.resmgr/FILTERS/zookeeper.conf, services/Zenoss.resmgr/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.saas/FILTERS/zookeeper.conf, services/Zenoss.saas/HBase/ZooKeeper/service.json, services/nfvi/FILTERS/zookeeper.conf, services/nfvi/Infrastructure/HBase/ZooKeeper/service.json, services/ucspm.lite/FILTERS/zookeeper.conf, services/ucspm.lite/Infrastructure/HBase/ZooKeeper/service.json, services/ucspm/FILTERS/zookeeper.conf, services/ucspm/Infrastructure/HBase/ZooKeeper/service.json
This is addresses the log filter for zookeeper logs per https://jira.zenoss.com/browse/ZEN-28088
=> The new zookeeper log filter and servicedef changes.

services/Zenoss.core.full/service.json, services/Zenoss.core/service.json, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/service.json, services/Zenoss.saas/service.json
For the hotfix release.
Fixes https://jira.zenoss.com/browse/ZEN-28498
=> Bump maintenance to 5.3.1

services/Zenoss.core.full/FILTERS/nginx_access.conf, services/Zenoss.core.full/FILTERS/nginx_error.conf, services/Zenoss.core/FILTERS/nginx_access.conf, services/Zenoss.core/FILTERS/nginx_error.conf, services/Zenoss.resmgr.lite/FILTERS/nginx_access.conf, services/Zenoss.resmgr.lite/FILTERS/nginx_error.conf, services/Zenoss.resmgr/FILTERS/nginx_access.conf, services/Zenoss.resmgr/FILTERS/nginx_error.conf, services/Zenoss.saas/FILTERS/nginx_access.conf, services/Zenoss.saas/FILTERS/nginx_error.conf, services/ucspm.lite/FILTERS/nginx_access.conf, services/ucspm.lite/FILTERS/nginx_error.conf, services/ucspm/FILTERS/nginx_access.conf, services/ucspm/FILTERS/nginx_error.conf
This set of changes fixes the issue specified in https://jira.zenoss.com/browse/CC-3874
=> Fixed the nginx logfilters.

services/Zenoss.core.full/service.json, services/Zenoss.core/service.json, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/service.json, services/Zenoss.saas/service.json
Prepare version number for 6.0.1
=> Bump version to 6.0.1

services/Zenoss.core.full/Infrastructure/RabbitMQ/service.json, services/Zenoss.core/Infrastructure/RabbitMQ/service.json, services/Zenoss.resmgr.lite/Infrastructure/RabbitMQ/service.json, services/Zenoss.resmgr/Infrastructure/RabbitMQ/service.json, services/Zenoss.saas/RabbitMQ/service.json, services/ucspm.lite/Infrastructure/RabbitMQ/service.json, services/ucspm/Infrastructure/RabbitMQ/service.json
https://jira.zenoss.com/browse/ZEN-29049
port https://github.com/zenoss/zenoss-service/pull/474
=> ZEN-29049 Limit RabbitMQ to one instance

services/Zenoss.core.full/service.json, services/Zenoss.core/service.json, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/service.json, services/Zenoss.saas/service.json
https://jira.zenoss.com/browse/ZEN-28945
=> ZEN-28945 Add "zenoss" public endpoint for zproxy

services/Zenoss.core.full/service.json, services/Zenoss.core/service.json, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/service.json, services/Zenoss.saas/service.json
=> Bump version 6.1.0 -> 6.1.1

services/Zenoss.cse/Infrastructure/memcached-session/-CONFIGS-/etc/sysconfig/memcached, services/Zenoss.cse/Infrastructure/memcached-session/service.json, services/Zenoss.cse/Zenoss/User Interface/Zauth/-CONFIGS-/opt/zenoss/etc/zope.conf, services/Zenoss.cse/Zenoss/User Interface/Zauth/service.json, services/Zenoss.cse/Zenoss/User Interface/Zope/-CONFIGS-/opt/zenoss/etc/zope.conf, services/Zenoss.cse/Zenoss/User Interface/Zope/service.json, services/Zenoss.cse/Zenoss/User Interface/zenapi/-CONFIGS-/opt/zenoss/etc/zenapi.conf, services/Zenoss.cse/Zenoss/User Interface/zenapi/service.json, services/Zenoss.cse/Zenoss/User Interface/zendebug/-CONFIGS-/opt/zenoss/etc/zendebug.conf, services/Zenoss.cse/Zenoss/User Interface/zendebug/service.json, services/Zenoss.cse/Zenoss/User Interface/zenreports/-CONFIGS-/opt/zenoss/etc/zenreports.conf, services/Zenoss.cse/Zenoss/User Interface/zenreports/service.json
https://jira.zenoss.com/browse/ZEN-29001
Adds the new memcached-session service for the new CSE service.
=> Add memcached-session for zope sessions in CSE

testdata/model/Zenoss.core.fake/Zenoss/User-Interface/Zauth/service.json
https://jira.zenoss.com/browse/ZEN-29001
The fake service should have fake healthchecks.
=> Replace real healhcheck with fake in the testdata service

services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json, services/Zenoss.cse/Zenoss/Metrics/MetricConsumer/-CONFIGS-/opt/zenoss/etc/metric-consumer-app/configuration.yaml, services/Zenoss.cse/Zenoss/Metrics/MetricConsumer/service.json, services/Zenoss.cse/service.json
Also, externalize the URL for zing-connector into a global config variable
=> Add endpoints for zing-connector

services/Zenoss.core.full/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.core/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.cse/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr.lite/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/ucspm/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, testdata/model/Zenoss.core.fake/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf
=> ZEN-29823: Add config option process_event_timeout

services/Zenoss.core.full/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.core/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.cse/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr.lite/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/ucspm/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, testdata/model/Zenoss.core.fake/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf
=> ZEN-29875: Add config option process_event_timeout

services/Zenoss.core.full/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.core/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.cse/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr.lite/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/Zenoss.resmgr/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, services/ucspm/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf, testdata/model/Zenoss.core.fake/Zenoss/Events/zeneventd/-CONFIGS-/opt/zenoss/etc/zeneventd.conf
=> ZEN-29920: change process_event_timeout to process-event-timeout

services/Zenoss.core.full/Zenoss/Metrics/MetricConsumer/service.json, services/Zenoss.cse/Zenoss/Metrics/MetricConsumer/service.json, services/Zenoss.resmgr/Zenoss/Metrics/MetricConsumer/service.json, services/ucspm/Zenoss/Metrics/MetricConsumer/service.json
[JIRA](https://jira.zenoss.com/browse/ZEN-30159)
=> ZEN-30159: increase metricconsumer RAM commitment to 2G

services/Zenoss.core.full/Infrastructure/memcached/service.json, services/Zenoss.core/Infrastructure/memcached/service.json, services/Zenoss.cse/Infrastructure/memcached/service.json, services/Zenoss.resmgr.lite/Infrastructure/memcached/service.json, services/Zenoss.resmgr/Infrastructure/memcached/service.json, services/ucspm.lite/Infrastructure/memcached/service.json, services/ucspm/Infrastructure/memcached/service.json
[Jira](https://jira.zenoss.com/browse/ZEN-29762)
=> ZEN-29762 increase memcached memory commitment

pkg/makefile
https://jira.zenoss.com/browse/CC-3559
Use the new serviced to compile service defs, to bring in new properties.
=> Use the new serviced to compile services

services/Zenoss.core.full/Zenoss/User Interface/Zauth/service.json, services/Zenoss.core.full/Zenoss/User Interface/Zope/service.json, services/Zenoss.core/Zenoss/User Interface/Zope/service.json, services/Zenoss.cse/Zenoss/User Interface/Zauth/service.json, services/Zenoss.cse/Zenoss/User Interface/Zope/service.json, services/Zenoss.cse/Zenoss/User Interface/zenapi/service.json, services/Zenoss.cse/Zenoss/User Interface/zendebug/service.json, services/Zenoss.cse/Zenoss/User Interface/zenreports/service.json, services/Zenoss.resmgr.lite/Zenoss/User Interface/Zope/service.json, services/Zenoss.resmgr/Zenoss/User Interface/Zauth/service.json, services/Zenoss.resmgr/Zenoss/User Interface/Zope/service.json, services/Zenoss.resmgr/Zenoss/User Interface/zenapi/service.json, services/Zenoss.resmgr/Zenoss/User Interface/zendebug/service.json, services/Zenoss.resmgr/Zenoss/User Interface/zenreports/service.json, services/ucspm.lite/Zenoss/User Interface/Zope/service.json, services/ucspm/Zenoss/User Interface/Zauth/service.json, services/ucspm/Zenoss/User Interface/Zope/service.json, services/ucspm/Zenoss/User Interface/zenapi/service.json, services/ucspm/Zenoss/User Interface/zendebug/service.json, services/ucspm/Zenoss/User Interface/zenreports/service.json
port from https://github.com/zenoss/zenoss-service/pull/564
=> ZEN-29781: Add deadlock healthchecks. Port from CC-3559.

makefile
ZING-1176
Add the -dev suffix to develop.
=> Add -dev suffix

services/Zenoss.cse/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf, services/Zenoss.cse/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf, services/Zenoss.resmgr.lite/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf, services/Zenoss.resmgr.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf, services/Zenoss.resmgr/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf, services/Zenoss.resmgr/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
[Jira](https://jira.zenoss.com/browse/ZEN-29764)
=> ZEN-29764 Default mariadb max_connections should match recommendations

services/Zenoss.core.full/Zenoss/Collection/localhost/zenhubworker/service.json, services/Zenoss.core/Zenoss/Collection/localhost/zenhubworker/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhubworker/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhubworker/service.json, services/ucspm.lite/Zenoss/Collection/localhost/zenhubworker/service.json, services/ucspm/Zenoss/Collection/localhost/zenhubworker/service.json
=> Fix zenhubworker 'running' healthcheck.

services/Zenoss.core.full/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf, services/Zenoss.core/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf, services/ucspm.lite/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf, services/ucspm/Zenoss/Collection/localhost/zenhub/-CONFIGS-/opt/zenoss/etc/zenhub.conf
=> Removed zenhub's job priority related options.

services/Zenoss.cse/Zenoss/Events/zeneventserver/service.json
=> ZING-1117: add pubsub metrics and graphs

services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
migration : https://github.com/zenoss/zenoss-prodbin/pull/3435
[JIRA](https://jira.zenoss.com/browse/ZEN-30890)
=> ZEN-30890: increase RAMCommitment for zenhub

services/Zenoss.core.full/service.json, services/Zenoss.core/service.json, services/Zenoss.cse/service.json, services/Zenoss.resmgr.lite/service.json, services/Zenoss.resmgr/service.json, services/ucspm.lite/service.json, services/ucspm/service.json
port https://github.com/zenoss/zenoss-service/pull/546/files
=> ZEN-29877: Lower modelindex default search limit

services/Zenoss.cse/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
Works with prodbin changes in this [PR](https://github.com/zenoss/zenoss-prodbin/pull/3497)
See notes in ZEN-31143 for details
=> ZEN-31143 - Fix for URL rewrite bug

makefile
=> Bump version for 7.0.8

services/Zenoss.cse/Infrastructure/memcached-session/-CONFIGS-/etc/sysconfig/memcached_supervisor.conf, services/Zenoss.cse/Infrastructure/memcached-session/service.json, services/Zenoss.cse/Infrastructure/memcached/-CONFIGS-/etc/sysconfig/memcached_supervisor.conf, services/Zenoss.cse/Infrastructure/memcached/service.json
Update memcached and memcached-session CSE definition to include the metric gathering script for memcached self-monitoring.
=> ZEN-31702 - Update default CSE service defs for memcached metrics

services/Zenoss.core.full/Zenoss/Collection/localhost/zenhubworker (adm)/service.json, services/Zenoss.core/Zenoss/Collection/localhost/zenhubworker (adm)/service.json, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhubworker (adm)/service.json, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhubworker (adm)/service.json
=> Set adm zenhubworker default instance to 1.

services/Zenoss.resmgr/Infrastructure/HBase/HMaster/service.json, services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.resmgr/Infrastructure/HBase/ZooKeeper/service.json, services/Zenoss.resmgr/Infrastructure/Solr/service.json, services/Zenoss.resmgr/Infrastructure/mariadb-events/service.json, services/Zenoss.resmgr/Infrastructure/mariadb-model/service.json, services/Zenoss.resmgr/Infrastructure/redis/service.json
Backport for the https://github.com/zenoss/zenoss-service/pull/609
=> ZEN-31872 Backport: disable OOMKiller on Databases

services/Zenoss.cse/Infrastructure/HBase/HMaster/service.json, services/Zenoss.cse/Infrastructure/HBase/RegionServer/service.json, services/Zenoss.cse/Infrastructure/HBase/ZooKeeper/service.json
=> Remove unnecessary changes

services/Zenoss.cse/Zenoss/Collection/localhost/localhost/zenping/-CONFIGS-/opt/zenoss/etc/zenping.conf
=> Update disable-correlator text in config

services/Zenoss.cse/Zenoss/Collection/localhost/zenhubworker (adm)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.cse/Zenoss/Collection/localhost/zenhubworker (default)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf
=> Add zenhub response timeout to zenhubworker config

services/Zenoss.core.full/Zenoss/Collection/localhost/zenhubworker (adm)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.core.full/Zenoss/Collection/localhost/zenhubworker (default)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.core/Zenoss/Collection/localhost/zenhubworker (adm)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.core/Zenoss/Collection/localhost/zenhubworker (default)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhubworker (adm)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhubworker (default)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhubworker (adm)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf, services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhubworker (default)/-CONFIGS-/opt/zenoss/etc/zenhubworker.conf
=> Add hub-response-timeout to zenhubworker config

services/Zenoss.cse/Infrastructure/RabbitMQ/-CONFIGS-/etc/rabbitmq/rabbit_supervisor.conf
=> Update supervisord rabbit config to use new script.

pkg/makefile
=> Use newer serviced version that knows about RunAs field.

services/Zenoss.resmgr/Infrastructure/mariadb-events/service.json, services/Zenoss.resmgr/Infrastructure/mariadb-model/service.json
It's related to https://github.com/zenoss/zenoss-prodbin/pull/3838
=> ZEN-32626 Add env variables to mariadb services

services/Zenoss.cse/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf, services/Zenoss.cse/Infrastructure/mariadb-events/service.json, services/Zenoss.cse/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf, services/Zenoss.cse/Infrastructure/mariadb-model/service.json
=> Update my.cnf for MariaDB 10.3

makefile, services/Zenoss.cse/service.json
=> Fix mariadb image tag.

migrations/src/zenservicemigration/migrations/run_some_services_as_zenoss.py, services/Zenoss.cse/Infrastructure/zing-api-proxy/service.json, services/Zenoss.cse/Infrastructure/zing-connector/service.json, services/Zenoss.cse/Zenoss/Collection/localhost/localhost/MetricShipper/service.json, services/Zenoss.cse/Zenoss/User Interface/zendebug/service.json
=> Migrate more services to use RunAs.

migrations/src/zenservicemigration/migrate.py
=> groupby requires a sorted list.
