zenoss/zenoss-service

- services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.saas/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/nfvi/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- testdata/model/Zenoss.core.fake/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
The pagespeed nginx plugin is involved in the serving of unsafe scripts which causes the RM UI to not render.
> ZEN-24758 WIP: turn pagespeed off to unblock QA

- services/Zenoss.core.full/Infrastructure/mariadb/-CONFIGS-/etc/my.cnf
- services/Zenoss.core/Infrastructure/mariadb/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- services/Zenoss.saas/mariadb-model/-CONFIGS-/etc/my.cnf
- services/ucspm.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- services/ucspm/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- testdata/model/Zenoss.core.fake/Infrastructure/mariadb/-CONFIGS-/etc/my.cnf
Remove the uintToInt method to provide backward compatibility. The default for mariadb-model and mariadb-events is now 3 which is the default CPU Commitment 4 minus 1.
> ZEN-21938 Remove uintToInt method

- services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.saas/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/nfvi/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- testdata/model/Zenoss.core.fake/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
Fixes broken RM UI rendering, which is caused seemingly by a request for i18n.js over HTTP creating a mixed content request, which is blocked by the browser. Adding a `Disallow *i18n*` to nginx.conf prevents insecure request for i18n.js from being bundled.
To test within an active deployment 
1. `serviced service attach Zenoss.core` or `serviced service attach Zenoss.resmgr[.lite]`
2. edit `/opt/zenoss/zproxy/conf/nginx.conf`
3. change the line `pagespeed off;` to `pagespeed on;`
4. and add the following line  `pagespeed Disallow '*i18n*';`
5. restart nginx `LD_LIBRARY_PATH=/opt/zenoss/zproxy/lib/ /opt/zenoss/zproxy/sbin/nginx -s reload`
6. Open the RM UI and bring up web developer tools. Load the Dashboard or Infrastructure page within the resmgr UI. Reload at least three times to ensure …
> Fix ZEN-24758: exclude i18n.js from pagespeed bundling

- services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.saas/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/nfvi/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/ucspm/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- testdata/model/Zenoss.core.fake/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
The exclusion of i18n.js is no longer needed to prevent nginx from serving mixed content bundles when pagespeed is enabled, now that `serviced/web/vhost.go` sets the X-Forwarded-Proto as https.
> Remove i18n.js exclusion in pagespeed bundles in light of CC-2679 fix

- services/Zenoss.core.full/Infrastructure/opentsdb/reader/service.json
- services/Zenoss.resmgr/Infrastructure/opentsdb/reader/service.json
- services/Zenoss.saas/opentsdb/reader/service.json
- services/nfvi/Infrastructure/opentsdb/reader/service.json
- services/ucspm/Infrastructure/opentsdb/reader/service.json
A reader service checks if the necessary HBase tables have been created by a writer instance.
The migration script for this change has been already merged. See https://github.com/zenoss/zenoss-prodbin/pull/1886.
> Add existence of HBase tables to OpenTSDB reader prereqs

- services/Zenoss.core.full/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core.full/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr.lite/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.saas/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.saas/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/nfvi/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/nfvi/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
Set the sampling period in the Hadoop Metrics 2 config to 15 secs. The migration script for this change has been already merged. See https://github.com/zenoss/zenoss-prodbin/pull/1890.
> Change the metrics reporting period of hbase services to 15 secs

- services/Zenoss.core.full/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.core.full/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.core/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.core/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.resmgr.lite/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.resmgr/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.saas/HBase/HMaster/service.json
- services/Zenoss.saas/HBase/RegionServer/service.json
- services/nfvi/Infrastructure/HBase/HMaster/service.json
- services/nfvi/Infrastructure/HBase/RegionServer/service.json
- services/ucspm.lite/Infrastructure/HBase/HMaster/service.json
- services/ucspm.lite/Infrastructure/HBase/RegionServer/service.json
- services/ucspm/Infrastructure/HBase/HMaster/service.json
- services/ucspm/Infrastructure/HBase/RegionServer/service.json
There was no data-points when monitoring CC from RM,
therefore respective graphs wasn't displaying data.
Add new metric config for data-points of the new graphs.
> ZEN-25579: add metric config for new graph

- services/Zenoss.core.full/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.core.full/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.core/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.core/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.resmgr.lite/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.resmgr/Infrastructure/HBase/HMaster/service.json
- services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/service.json
- services/Zenoss.saas/HBase/HMaster/service.json
- services/Zenoss.saas/HBase/RegionServer/service.json
- services/nfvi/Infrastructure/HBase/HMaster/service.json
- services/nfvi/Infrastructure/HBase/RegionServer/service.json
- services/ucspm.lite/Infrastructure/HBase/HMaster/service.json
- services/ucspm.lite/Infrastructure/HBase/RegionServer/service.json
- services/ucspm/Infrastructure/HBase/HMaster/service.json
- services/ucspm/Infrastructure/HBase/RegionServer/service.json
There was no data-points when monitoring CC from RM,
therefore respective graphs wasn't displaying data.
This is additional fix for https://github.com/zenoss/zenoss-service/pull/327
Add new metric source for graph datapoints and change datapoints name to the same as legend.
[Jira](https://jira.zenoss.com/browse/ZEN-25579)
> ZEN-25579: add metric source to graph datapoints, change datapoints name

- services/datastack/Infrastructure/Solr/-CONFIGS-/opt/solr/zenoss/etc/solr.in.sh
- services/datastack/Infrastructure/Solr/service.json
- Add per container solr configuration file
- Initialize solr on startup.
Note that this service definition uses a version of the zenoss/solr image which has not yet been pushed to docker hub; please do not merge until that has occurred.
See related https://github.com/zenoss/solr-image/pull/2
> Initialize solr on service startup

- pkg/makefile
We need to update to a version of serviced that recognizes StartLevel, EmergencyStop, and EmergencyStopLevel
> Update version of serviced used to compile templates

- services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/Zenoss.core/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/nfvi/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/ucspm.lite/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
- services/ucspm/Zenoss/Collection/localhost/localhost/zenmodeler/service.json
Removed devices, eventQueueLength, and timedOut from both metrics and graphs in zenmodeler service.json
for each defined service.
These graphs were empty or otherwise not useful and were removed in a service migration, but the base definitions had
not been brought up to date to match.
> ZEN-27213 Remove old metrics from GraphConfigs

- pkg/makefile
https://github.com/control-center/serviced/pull/3479 added a new property, `IsAudit`, to the `LogConfig` object.  
This PR picks up the latest CC build which includes that change so that service definitions can be compiled with the new property.
Fix CC-3484
> Update SERVICED_ARCHIVE for audit logging

- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenwebtx/-CONFIGS-/opt/zenoss/etc/zenwebtx.conf
- services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenwebtx/-CONFIGS-/opt/zenoss/etc/zenwebtx.conf
- services/Zenoss.saas/localhost/localhost/zenwebtx/-CONFIGS-/opt/zenoss/etc/zenwebtx.conf
Fixes [ZPS-1288](https://jira.zenoss.com/browse/ZPS-1288).
> ZPS-1288: Remove terminal escape sequences from config files.

- services/Zenoss.core.full/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/Zenoss.core.full/service.json
- services/Zenoss.core/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/Zenoss.core/service.json
- services/Zenoss.resmgr.lite/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/Zenoss.resmgr.lite/service.json
- services/Zenoss.resmgr/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/Zenoss.resmgr/service.json
- services/ucspm.lite/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/ucspm.lite/service.json
- services/ucspm/-CONFIGS-/etc/zproxy/zproxy_supervisor.conf
- services/ucspm/service.json
Zproxy has been updated for Zenoss.core, Zenoss.core.full, Zenoss.resmgr, and Zenoss.resmgr.lite.
Zproxy is now run via supervisord.
New zenossStatsView.py process added to zproxy supervisord process to track metrics.
> ZEN-27333 Add metrics collection to zproxy

- services/Zenoss.resmgr/service.json
- services/ucspm/service.json
Backport fix/ZEN-27858: zendebug public VHost should be disabled by default
> Fix/ZEN-27867: backport #415 to disable zendebug VHost by default

- services/Zenoss.core.full/Infrastructure/RabbitMQ/service.json
- services/Zenoss.core/Infrastructure/RabbitMQ/service.json
- services/Zenoss.resmgr.lite/Infrastructure/RabbitMQ/service.json
- services/Zenoss.resmgr/Infrastructure/RabbitMQ/service.json
- services/Zenoss.saas/RabbitMQ/service.json
- services/nfvi/Infrastructure/RabbitMQ/service.json
- services/ucspm.lite/Infrastructure/RabbitMQ/service.json
- services/ucspm/Infrastructure/RabbitMQ/service.json
https://jira.zenoss.com/browse/ZEN-28242
Cherry picked from https://github.com/zenoss/zenoss-service/pull/437 removing the rabbitmq.conf log filters.  This was changed to make the rabbitmq servicedef log file name match the actual log file name in the container.  This will allow rabbitmq log messages to flow through logstash to elastic.
> Fix the rabbitmq log file name and location for all 8 products.

- services/Zenoss.core.full/service.json
- services/Zenoss.core/service.json
- services/Zenoss.resmgr.lite/service.json
- services/Zenoss.resmgr/service.json
- services/Zenoss.saas/service.json
Because we're releasing 5.3.1 as a hotfix and versioning the tip of support/5.3.x to 5.3.2
> Bump version to 5.3.2

- services/Zenoss.core.full/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core.full/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.core.full/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.core/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.core/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr.lite/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.resmgr.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.resmgr/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.resmgr/Infrastructure/mariadb-events/service.json
- services/Zenoss.resmgr/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.resmgr/Infrastructure/mariadb-model/service.json
- services/Zenoss.saas/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/ucspm.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/ucspm/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/ucspm/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- testdata/model/Zenoss.core.fake/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
Created gather.py variant for mariadb-model and mariadb-events in prodbin.
Modified mariadb-model and mariadb-events to gather database size metrics in prodbin.
Made changes to hadoop configs to collect additional metrics in HMaster.
> ZEN-27336 Collect storage metrics from HBase and Maria

- services/Zenoss.core.full/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core.full/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.core/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr.lite/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.resmgr/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.saas/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/Zenoss.saas/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm.lite/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm/Infrastructure/HBase/HMaster/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
- services/ucspm/Infrastructure/HBase/RegionServer/-CONFIGS-/opt/hbase/conf/hadoop-metrics2-hbase.properties
HMaster hadoop metrics2 was not collecting the metric storeFileSize
RegionServer does.
The filters have been modified to collect storeFile\w* instead of storeFile\w+
> ZEN-27336 Fix: Collect storage metrics from RegionServer

- services/Zenoss.core.full/FILTERS/zeneventserver.conf
- services/Zenoss.core/FILTERS/zeneventserver.conf
- services/Zenoss.resmgr.lite/FILTERS/zeneventserver.conf
- services/Zenoss.resmgr/FILTERS/zeneventserver.conf
- services/Zenoss.saas/FILTERS/zeneventserver.conf
- services/ucspm.lite/FILTERS/zeneventserver.conf
- services/ucspm/FILTERS/zeneventserver.conf
This fix addresses the issue specified in https://jira.zenoss.com/browse/ZEN-28566.
> Fixed the multiline to be explicit and handle a datetime parse failure

- services/Zenoss.core.full/Zenoss/Metrics/CentralQuery/service.json
- services/Zenoss.core/Zenoss/Metrics/CentralQuery/service.json
- services/Zenoss.resmgr.lite/Zenoss/Metrics/CentralQuery/service.json
- services/Zenoss.resmgr/Zenoss/Metrics/CentralQuery/service.json
- services/Zenoss.saas/CentralQuery/service.json
- services/ucspm.lite/Zenoss/Metrics/CentralQuery/service.json
- services/ucspm/Zenoss/Metrics/CentralQuery/service.json
in order to drop cache on writer after reidentifying a device.
> ZEN-28753: Add opentsdb writer endpoint to centralquery

- services/Zenoss.core.full/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/Zenoss.core.full/Zenoss/Metrics/MetricShipper/service.json
- services/Zenoss.core/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/Zenoss.core/Zenoss/Metrics/MetricShipper/service.json
- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/Zenoss.resmgr.lite/Zenoss/Metrics/MetricShipper/service.json
- services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/Zenoss.resmgr/Zenoss/Metrics/MetricShipper/service.json
- services/ucspm.lite/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/ucspm.lite/Zenoss/Metrics/MetricShipper/service.json
- services/ucspm/Zenoss/Collection/localhost/localhost/MetricShipper/service.json
- services/ucspm/Zenoss/Metrics/MetricShipper/service.json
Add rateOptions for metricshipper rates datapoints to make RM graphs congruent with CC graphs;
also fix will prevent negative values in metricshipper CC graphs
[Jira](https://jira.zenoss.com/browse/CC-3937)
> CC-3937 add rateOptions for counters

- services/Zenoss.cse/Infrastructure/zing-connector/service.json
The CSE running in GCP needs to pull images from GCR, because the CSE in GCP does not have access to `registry.zing.zenoss.eng`
> Use GCR instead of registry.zing so CSE deployment works

- makefile
- services/Zenoss.cse/Infrastructure/zing-connector/-CONFIGS-/etc/zing-connector.yml
- services/Zenoss.cse/Infrastructure/zing-connector/service.json
This allows us to inject the image tag for the zing-connector image.  Note that this code will be used by complimentary changes in the product-assembly repo, which are available in this [PR](https://github.com/zenoss/product-assembly/pull/661)
> Refine zing connector

- services/Zenoss.cse/Infrastructure/zing-connector/-CONFIGS-/etc/zing-connector.yml
Model-ingest and metric-ingest stanzas from Zenoss.cse zing-connector.yml
> Removed deprecated options from zing-connector.yml

- services/Zenoss.cse/Infrastructure/zing-connector/service.json
Both zendev and the build process will swap in the right value at build time.
> Restore the right image ID for zing-connector

- services/Zenoss.cse/Zenoss/Collection/localhost/localhost/zenucsevents/-CONFIGS-/opt/zenoss/etc/zenucsevents.conf
- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/localhost/zenucsevents/-CONFIGS-/opt/zenoss/etc/zenucsevents.conf
- services/Zenoss.resmgr/Zenoss/Collection/localhost/localhost/zenucsevents/-CONFIGS-/opt/zenoss/etc/zenucsevents.conf
- services/ucspm.lite/Zenoss/Collection/localhost/localhost/zenucsevents/-CONFIGS-/opt/zenoss/etc/zenucsevents.conf
- services/ucspm/Zenoss/Collection/localhost/localhost/zenucsevents/-CONFIGS-/opt/zenoss/etc/zenucsevents.conf
Fixes [ZPS-797](https://jira.zenoss.com/browse/ZPS-797).
> Lower default configsipsize from 25 to 5 in zenucsevents.conf

- services/Zenoss.cse/service.json
https://jira.zenoss.com/browse/ZEN-30235
Default the whitelist to alphacorp.  For a cse-deploy job, this is replaced by the tenant in provision.  For local zendev this will be alphacorp, which matches the tenant assigned via auth0 (if configured for that).
> Default the whitelist to alphacorp; this is replaced in cse-provision

- services/Zenoss.cse/service.json
https://jira.zenoss.com/browse/ZEN-30248
Add the emailkey property to global.conf.  We'll use this to try to parse out the email address from the access token (for db connections).
> Add the emailkey property to global.conf

- services/Zenoss.core.full/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/Zenoss.core.full/Infrastructure/Solr/service.json
- services/Zenoss.core/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/Zenoss.core/Infrastructure/Solr/service.json
- services/Zenoss.cse/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/Zenoss.cse/Infrastructure/Solr/service.json
- services/Zenoss.resmgr.lite/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/Zenoss.resmgr.lite/Infrastructure/Solr/service.json
- services/Zenoss.resmgr/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/Zenoss.resmgr/Infrastructure/Solr/service.json
- services/ucspm.lite/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/ucspm.lite/Infrastructure/Solr/service.json
- services/ucspm/Infrastructure/Solr/-CONFIGS-/var/solr/log4j.properties
- services/ucspm/Infrastructure/Solr/service.json
Solr logs was filling logstash up at a rate so fast that it would
have filled up isvcs before the next purge cycle.
Set solr log level to WARN to reduce number of logs.
[JIRA](https://jira.zenoss.com/browse/ZEN-29878)
> ZEN-29878: add log config file and set solr log level to WARN

- services/Zenoss.cse/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-disable-basic-auth.conf
- services/Zenoss.cse/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
https://jira.zenoss.com/browse/ZEN-30567
Prevent using basic authentication from the GLB.  Basic auth from an internal call will still work as expected.  We also deny access to the login page so you can't login with basic auth, bypassing
Auth0.
> Disable basic auth on the GLB; disable login page

- services/Zenoss.core.full/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.cse/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhub/service.json
- services/ucspm/Zenoss/Collection/localhost/zenhub/service.json
From the start zenhub consuming more than 1GB of RAM
that is why we increase RAMCommitment to 2GB
[JIRA&INFO](https://jira.zenoss.com/browse/ZEN-29393?focusedCommentId=130995&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-130995)
> ZEN-29393: increase RAMCommitment for zenhub

- pkg/makefile
port from https://github.com/zenoss/zenoss-service/pull/565
> ZEN-29781: Use the new serviced to compile services. Port from CC-3559.

- services/Zenoss.cse/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
https://jira.zenoss.com/browse/ZEN-30731
Performance metrics were able to use basic auth through the GLB.  Block all api calls through the GLB using basic authentication.
> Disable basic auth on GLB for api calls

- hack/Dockerfile
> Use ubuntu:xenial as base for Docker image.

- services/Zenoss.core.full/Zenoss/User Interface/Zauth/service.json
- services/Zenoss.resmgr/Zenoss/User Interface/Zauth/service.json
- services/ucspm/Zenoss/User Interface/Zauth/service.json
Fixes ZEN-30871.
Note: the ucspm.lite, Zenoss.resmgr.lite, and Zenoss.core application templates do not have a Zauth service.
> Increase Zauth instance count to 2.

- services/Zenoss.core.full/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.core.full/Zenoss/Collection/localhost/zenhubworker/service.json
- services/Zenoss.core.full/Zenoss/Events/zeneventd/service.json
- services/Zenoss.core.full/Zenoss/User Interface/Zope/service.json
- services/Zenoss.core/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.core/Zenoss/Collection/localhost/zenhubworker/service.json
- services/Zenoss.core/Zenoss/Events/zeneventd/service.json
- services/Zenoss.core/Zenoss/User Interface/Zope/service.json
- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.resmgr.lite/Zenoss/Collection/localhost/zenhubworker/service.json
- services/Zenoss.resmgr.lite/Zenoss/Events/zeneventd/service.json
- services/Zenoss.resmgr.lite/Zenoss/User Interface/Zope/service.json
- services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhub/service.json
- services/Zenoss.resmgr/Zenoss/Collection/localhost/zenhubworker/service.json
- services/Zenoss.resmgr/Zenoss/Events/zeneventd/service.json
- services/Zenoss.resmgr/Zenoss/User Interface/Zope/service.json
- services/ucspm.lite/Zenoss/Collection/localhost/zenhub/service.json
- services/ucspm.lite/Zenoss/Collection/localhost/zenhubworker/service.json
- services/ucspm.lite/Zenoss/Events/zeneventd/service.json
- services/ucspm.lite/Zenoss/User Interface/Zope/service.json
- services/ucspm/Zenoss/Collection/localhost/zenhub/service.json
- services/ucspm/Zenoss/Collection/localhost/zenhubworker/service.json
- services/ucspm/Zenoss/Events/zeneventd/service.json
- services/ucspm/Zenoss/User Interface/Zope/service.json
Services getting a PREFER_SEPARATE HostPolicy are zenhub, zenhubworker, zeneventd, and Zope.
Fixes ZEN-22178.
> Set HostPolicy to PREFER_SEPARATE.

- makefile
According to the ticket https://jira.zenoss.com/browse/ZING-1650 I added the string to the makefile
> ZING-1650  The service def build for api-key-proxy is using the wrong image tag 

- services/Zenoss.core.full/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.core/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.cse/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr.lite/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
- services/Zenoss.resmgr/-CONFIGS-/opt/zenoss/zproxy/conf/zproxy-nginx.conf
These headers were added to increase the security level.
What is every header for:
**_Referrer-Policy "no-referrer-when-downgrade":_** the destination site won't receive information about the origin the user came from when user will go from https to HTTP. We do not need to block this completely since we do not have sensitive information in URL.
**_X-Content-Type-Options "nosniff always":_** this will prevent the browser from doing MIME-sniffing and then inserting insecure plain/text into the page as an HTML.
**_Strict-Transport-Security "max-age=31536000; includeSubdomains":_** this will force the UI to connect with a server only throught the HTTPS
[JIRA&DEMO](https://jira.zenoss.com/browse/ZING-1646)
> ZING-1646: add additional security headers to nginx config

- pkg/makefile
Updated serviced to compile services because of new parameters in the service definition that we started support from CC 1.6.5
> CZ: disable OOMKiller on Databases

- services/Zenoss.cse/Infrastructure/mariadb-events/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.cse/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf
- services/Zenoss.cse/Infrastructure/mariadb-events/service.json
- services/Zenoss.cse/Infrastructure/mariadb-model/-CONFIGS-/etc/mariadb/mariadb_supervisor.conf
- services/Zenoss.cse/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- services/Zenoss.cse/Infrastructure/mariadb-model/service.json
* Replaced call to mysqld_safe with mysqld. The mysqld_safe command is a wrapper that has the same functionality as supervisord and so, in effect, is redundant.
* Added 'user' option to supervisord managed programs to control security.
* Allow more time for mariadb to shut down before supervisord kills the process.
Fixes ZEN-32261.
> Let supervisord manage mariadb directly.

- services/Zenoss.cse/Zenoss/Collection/localhost/zenhubiworker/service.json
- services/Zenoss.cse/Zenoss/Collection/localhost/zenhubworker (adm)/service.json
- services/Zenoss.cse/Zenoss/Collection/localhost/zenhubworker (default)/service.json
Fixes ZEN-32378.
This PR contains adds a "hub" tag to the hub services, i.e. the zenhubworker and zenhubiworker services.
> Add 'hub' to Tags field of hub services.

- services/Zenoss.cse/Zenoss/Events/zeneventserver/service.json
This pull request replaces the name of healthcheck 'mariadb_answering' with 'mariadb_events_anwering' for clarity.
Also, the script for healthcheck was changed, it used the credentials for zodb when zeneventserver actually connects to the zep.
These changes fix the problem when healthcheck is failed after changing a password for 'zenoss' user in mariadb-events
> ZEN-32689 Update 'mariadb_answering' healthcheck in zeneventserver

- services/Zenoss.resmgr/Zenoss/Events/zeneventserver/service.json
This pr replaces the name of healthcheck 'mariadb_answering' with 'mariadb_events_anwering' for clarity.
Also, the script for healthcheck was changed, it used the credentials for zodb when zeneventserver actually connects to the zep.
These changes fix the problem when healthcheck is failed after changing a password for 'zenoss' user in mariadb-events
> ZEN-32690 Update 'mariadb_answering' healthcheck in zeneventserver

- .gitignore
- hack/Dockerfile
- image/Dockerfile.in
- image/add_user.sh
- make_template.sh
- makefile
- migrations/makefile
- migrations/setup.py
- migrations/src/zenservicemigration/migrate.py
- migrations/src/zenservicemigration/migrations/fix_mariadb_configs_for_10_3.py
- pkg/makefile
The 'zenservicemigration' package is designed to run during the upgrade of a Zenoss system without relying on ZODB.
The inaugural migration is to migrate the mariadb services to use the MariaDB 10.3 image.
Fixes ZEN-32769.
> Add service migration package.

- migrations/src/zenservicemigration/migrations/fix_mariadb_configs_for_10_3.py
- services/Zenoss.core.full/Infrastructure/mariadb/-CONFIGS-/etc/my.cnf
- services/Zenoss.core/Infrastructure/mariadb/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr.lite/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr.lite/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr/Infrastructure/mariadb-events/-CONFIGS-/etc/my.cnf
- services/Zenoss.resmgr/Infrastructure/mariadb-model/-CONFIGS-/etc/my.cnf
MariaDB 10.3.22 has a bug that prevents crash recovery when the instance count is greater an 1.
Fixes ZEN-32835.
> Set innodb_buffer_pool_instances to 1.

- migrations/src/zenservicemigration/migrations/data/zenjobs-celery3126upgrade_zodb.conf
- services/Zenoss.cse/Zenoss/User Interface/zenjobs/-CONFIGS-/opt/zenoss/etc/zodb.conf
* Turn off remote cache (memcache)
* Specify additional cache configs Zenoss normally uses but were previously left out of zenjobs' relstorage/ZODB configuration.
ZEN-33096.
> Update relstorage/ZODB cache in zenjobs.

- migrations/src/zenservicemigration/migrations/data/zenjobs-celery3126upgrade_zenjobs.conf
- migrations/src/zenservicemigration/migrations/update_zenjobs_for_celery31.py
- services/Zenoss.cse/Zenoss/User Interface/zenjobs/-CONFIGS-/opt/zenoss/etc/zenjobs.conf
- services/Zenoss.cse/service.json
Multiple services (Zope, etc) need access to the job-expires option so move it to the global.conf file.
Fixes ZEN-33101.
> zenjobs' job-expires option should be global.

- migrations/src/zenservicemigration/migrations/fix_collectorredis_replication.py
- services/Zenoss.cse/Zenoss/Collection/localhost/localhost/collectorredis/service.json
Changes the collectorredis command so that all non-zero-instances are replication slaves.
Fixes ZEN-32686.
> Reliably enable replication for collectorredis.

- migrations/src/zenservicemigration/migrations/add_opentsdb_endpoints.py
This script adds endpoints during the upgrade which are needed
for Capacity ZenPack
> ZEN-32003 Add migration script to add the opentsdb-reader endpoint
